function gettranslate(id){
    var en = 
    {
        "search_vaults":"Searching vaults",
        "personal":"Personal",
        "vault":"Vault",
        "passkeys":"Passkeys",
        "docsmenu":"<i class=\"fa fa-id-card\" ></i>Documents",
        "isenhas":"iSenhas",
        "description_label":"Note (optional)",
        "description_title":"Note",
        "favorite_pix":"Favorite transfer code",
        "favorite_note":"Favorite note",
        "favorite_password":"Favorite password",
        "favorite_document":"Favorite document",
        "search_notes":"Searching notes",
        "search_notes_error":"Error while searching notes. Update the page and try again. Code",
        "search_statistics_error":"Error while searching statistics. Update the page and try again. Code",
        "add_note":"Creating note",
        "add_note_error":"Error while creating note. Update the page and try again. Code",
        "add_user":"Creating user",
        "add_user_error":"Error while creating user. Update the page and try again. Code",
        "no_selection":"No note selected.",
        "remove_note":"Removing notes",
        "remove_note_error":"Error while removing notes. Update the page and try again. Code",
        "remove_user":"Removing user",
        "remove_user_error":"Error while removing user. Update the page and try again. Code",
        "update_note":"Updating note",
        "update_note_error":"Error while updating note. Update the page and try again. Code",
        "update_user":"Updating user",
        "update_user_error":"Error while updating user. Update the page and try again. Code",
        "search_passwords":"Searching passwords",
        "search_passwords_error":"Error while searching passwords. Update the page and try again. Code",
        "search_users":"Searching users",
        "search_users_error":"Error while searching users. Update the page and try again. Code",
        "add_password":"Creating password",
        "add_password_error":"Error while creating password. Update the page and try again. Code",
        "no_password_selected":"No password selected",
        "no_user_selected":"No user selected",
        "remove_password":"Removing passwords",
        "remove_document":"Removing documents",
        "remove_password_error":"Error while removing passwords. Update the page and try again. Code",
        "update_password":"Updating password",
        "update_document":"Updating document",
        "update_password_error":"Error while updating password. Update the page and try again. Code",
        "code_notfound":"Code not found. Refresh the page and try again.",
        "login_error":"Error while authenticating. Refresh the page and try again. Code",
        "weak":"Weak",
        "very_weak":"Very weak",
        "regular":"Regular",
        "strong":"Strong",
        "very_strong":"Very strong",
        "home":"HOME",
        "repeated":"Repeated",
        "about":"ABOUT",
        "gallery":"GALLERY",
        "team" : "TEAM",
        "download":"DOWNLOAD",
        "price":"PLANS",
        "contact":"CONTACT",
        "my_passwords":"LOGIN",
        "title_start":"Manage passwords with intelligence and security.",
        "title_sub1":"Access from anywhere through apps, website or browser extension.",
        "title_sub2":"Use smart folder algorithm and automatic icon detection to organize.",
        "title_sub3":"Create strong and random passwords in a secure, AES-256 encrypted environment.",
        "how_works" :"How it works?",
        "how_works_sub":"Quick and simple setup to access your passwords from any device with <br>Biometric sensor or your Unique password.",
        "how_works_import" :"Import",
        "how_works_import_sub":"Import your passwords from Google, LastPass, Dashlane, Bitwarden, SafeInCloud or Custom Files.",
        "how_works_generate":"Generate",
        "how_works_generate_sub":"Generate strong passwords of up to 30 digits with special characters, capital letters and numbers.",
        "how_works_autofill":"Autofill",
        "how_works_autofill_sub":"Fill login fields quickly on any device.",
        "how_works_scan":"Scan",
        "how_works_scan_sub":"Check the health of your passwords in the alert list and take actions to improve your security.",
        "prepare_sub1": "iSenhas has never suffered a breach. But if one occurs, it will not put your vault's confidential data at risk.",
        "prepare_sub2": "Each item is protected with a AES-256 encryption before being stored in iSenhas cloud backup.",
        "prepare_sub4": "For offline storage on the device itself, iSenhas uses a PBKDF2 derivation of the Access password to encrypt items with AES-256 GCM, ensuring maximum protection even without an internet connection.",
        "prepare_sub8":"iSenhas also values ​​transparency. Part of the source code is public and can be accessed on GitHub, allowing the community to analyze, audit, and monitor the evolution of the project's security.",
        "prepare_desc": "Advanced security.",
        "prepare_title": "Is iSenhas secure?",
        "get_app":"GET APP",
        "explore_title":"Explore the solution",
        "explore_sub":"See the details we've prepared on each screen to<br>transform your password experience.",
        "us_title" : "Meet the founder!",
        "us_sub":"The mind behind iSenhas and the idea of ​​uncomplicated security.",
        "davi_title":"Founder",
        "davi_sub":"Davi is the engineer and creator behind iSenhas.<p>With over 10 years of experience, he has worked for multinationals and won innovation awards during his career.",
        "lisi_title":"Manager and Accountant",
        "lisi_sub":"Graduated in Administration and Accounting, she directs iSenhas on the path of remaining a simple and useful tool. Experienced in the industry, outlines the strategic planning and marketing of the product.",
        "review1":"Great and uncomplicated app. Serves you perfectly. I recommend. Congratulations to the developer.",
        "review2":"Super functional and practical application to use, I kept my passwords in the notebook, without much privacy, with the App it was much safer.",
        "review3":"Very intuitive app, delivers what it promises. I can record all my passwords securely.",
        "android_user":"Android User",
        "ios_user":"iOS User",
        "download_title":"Download",
        "download_sub":"Click on one of the options to be directed to the store of each solution.<br>iSenhas is not provided outside official stores.",
        "ios_title":"iOS/MacOS app",
        "ios_sub":"Download the app that is top 100 most downloaded in the App Store Brazil.",
        "android_title":"Android app",
        "android_sub":"Download your passwords on Android tables and smartphones.",
        "chrome_title":"Chrome extension",
        "chrome_sub":"Increase your speed when accessing websites with the Chrome extension.",
        "brave_title":"Brave extension",
        "brave_sub":"Increase your security when accessing websites with the Brave extension.",
        "edge_title":"Edge extension",
        "edge_sub":"Gain productivity in the official Microsoft browser.",
        "firefox_title":"Firefox extension",
        "firefox_sub":"Manage and fill passwords in Firefox browser.",
        "safari_title":"Safari extension",
        "safari_sub":"Use iSenhas on the official Apple browser.",
        "questions_title":"Our answers to the most common questions",
        "questions1":"Does anyone have access to my passwords?",
        "questions1_answer":"No. You are our customer and not our product. Your passwords are protected so that no one but you has access.",
        "questions2":"Does anyone have access to my passwords?",
        "questions2_answer":"No. You are our customer and not our product. Your passwords are protected so that no one but you has access.",
        "questions3_answer":"Compatibility: Password manager programs are cross-platform and cross-browser. Browser password managers are not: they are limited to that specific browser.<br>Password generator: The biggest enemy of your accounts online is password reuse. If you do that, and the password is cracked, all other accounts will be exposed. So it will be very easy for the attacker to hack your accounts - currently this trick is the most common.",
        "questions3":"Why use iSenhas instead of web browser password manager?",
        "questions4_answer":"Yes. You can also store notes and reminders securely.",
        "questions4":"Can I store anything else besides passwords?",
        "years_appstore":"Years at App Store",
        "happy_customers":"Happy customers",
        "top_appstore":"Top App Store Brazil",
        "cups_coffe":"Cups of coffe",
        "fast_support":"Fast support",
        "plans_title":"Plans",
        "plans_sub":"Check out the plans available within the Google Play and App Store.<br>You will be able to acquire them through the apps.",
        "plans_free":"FREE",
        "plans_price":"$ 0.00",
        "plans_month":"Per month",
        "plans_get":"GET APP",
        "plan1_arg1":"<b>Local</b> storage of up to 5 passwords.",
        "plan1_arg2":"Smart folders <b>algorithm</b>.",
        "plan1_arg3":"<b>Automatic</b> icon detection.",
        "plan1_arg4":"Password <b>generator</b>.",
        "plan1_arg5":"List with security <b>alerts</b>.",
        "plan1_arg6":"<b>Autocomplete</b> user logins.",
        "plan1_arg7":"3 breach scans in <b>Dark Web</b>.",
        "plan3_arg6":"Support 24/7.",
        "premium_price":"$ 1.99",
        "plan2_arg1":"<b>Unlimited cloud</b> storage.",
        "plan2_arg2":"<b>All</b> free plan features.",
        "plan2_arg3":"<b>Unlimited</b> Dark Web breaches scan.",
        "plan2_arg4":"Storage password <b>in the cloud<b/>.",
        "plan2_arg5":"List with security alerts.",
        "plan2_arg6":"Autocomplete user logins.",
        "plan2_arg7":"<b>Secure</b> password sharing.",
        "plan2_arg8":"Access your passwords in <b>any device</b>.",
        "plan2_arg9":"Passwords <b>recovery</b>.",
        "news_title":"Latest news",
        "news_sub":"Stay on top of what we're working on,<br>new features and achievements.",
        "achievements":"Achievements",
        "achievements_sub":"iSenhas was featured by Apple in \"Popular Apps\" list.",
        "know_more":"KNOW MORE",
        "new2_title":"How to use iSenhas on computer?",
        "new2_sub1":"Videos",
        "new2_sub2":"Tutorial",
        "new2_desc":"See how easy and safe it is to use iSenhas on your computer.",
        "new3_title":"Who does the iSenhas?",
        "new3_sub1":"Davi Orzechowski",
        "new3_sub2":"Founder",
        "new3_desc":"Want to know a little more about the history of iSenhas? Watch this video that tells the beginning of our trajectory.",
        "contact_title":"Talk to us",
        "contact_sub":"Did you miss something or find a problem? Write to us.<br>We will reply as soon as possible.",
        "contact_name":"Complete name*",
        "contact_email":"Email*",
        "contact_text":"Write to us here! To speed up the service, inform your operating system (iOS or Android).",
        "contact_send":"SEND",
        "contact_ok":"Thanks for your message. We will contact you as soon as possible.",
        "img1":"/images/senha-en.webp",
        "img2":"/images/pastas-en.webp",
        "img3":"/images/alertas-en.webp",
        "img4":"/images/web-en.webp",
        "img5":"/images/chrome-en.webp",
        "img6":"/images/login-en.webp",
        "googlesafe":"/images/googlesafe-en.png",
        "popularapps":"/images/popularapps.png",
        "appswelove":"/images/appswelove.png",
        "apple_ecamp":"/images/apple_ecamp.png",
        "appswelove_link":"https://www.instagram.com/p/C-3u1XjJeON/",
        "popularapps_link":"https://www.instagram.com/p/C92SvgRO3Ku/",
        "social":"Find us in social media:",
        "business_price":"$ 1.10",
        "business_month":"each user/month",
        "business_get":"GET APP",
        "business_download":"DOWNLOAD PDF",
        "plan3_arg1":"Premium features for <b>all users</b>.",
        "plan3_arg2":"Users management with <b>profiles</b>.",
        "plan3_arg3":"Dedicated dashboard for passwords <b>management</b>.",
        "plan3_arg4":"<b>Alert</b> security list.",
        "users":"Users",
        "add_user_limit":"The limit of users was reached. Please, contact iSenhas sales to upgrade your Business plan.",
        "add_user_already_exists":"This user already exists. Error",
        "search_statistics":"Getting statistics. This could take a while",
        "bank":"Banks",
        "gov":"Government",
        "market":"Market",
        "travel":"Travel",
        "document":"Documents",
        "internet":"Operators",
        "website":"Websites | Apps",
        "access":"Access",
        "magazine":"Magazines",
        "other":"Others",
        "notes":"Notes",
        "strong_password":"Strong",
        "regular_password":"Regular",
        "weak_password":"Weak",
        "shared_by" : "Shared by",
        "share":"Share",
        "plan3_arg5" : "<b>Sharing</b> passwords between users.",
        "sending_notifications":"Sending notifications",
        "passwords":"Passwords",
        "login_title":"iSenhas WEB",
        "login_desc1":"1. Open the <b>iSenhas</b> app, tap the<img style=\"height:30px;width: 30px;margin-left: 5px;margin-right: 5px;margin-bottom: 5px;\" alt=\"Qries\" src=\"/images/iconsmart/readbutton.png\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@fat\"/>button and authenticate with the <b>QRCode</b> above (available for Premium users).</h3>",
        "login_desc2":"2. Click on <b>SIGN IN</b> to access iSenhas WEB.",
        "btn_login":"SIGN IN",
        "login_loading":"Searching user and preparing a safe environment...",
        "login_checkbox":"Keep me connected",
        "notas_loading":"Searching notes..",
        "name":"Name",
        "password":"Password",
        "copy":"Copy",
        "note_search":"Search note...",
        "edit":"Edit",
        "passwordsmenu":"<i class=\"fas fa-key\" ></i>Passwords",
        "notesmenu":"<i class=\"fas fa-sticky-note\" ></i>Notes",
        "logoutmenu":"<i class=\"fas fa-sign-out-alt\" ></i>Logout",
        "notes":"Notes",
        "buttonadd":"ADD",
        "buttonremove":"REMOVE",
        "new_note":"New note",
        "note":"Note",
        "ex_note":"Ex.: My note",
        "ex_note_desc":"Ex.: fea8hjaejJ(U",
        "cancelbutton":"CANCEL",
        "remove_notes":"Remove notes",
        "remove_notes_desc":"Do you really want to remove the selected notes?",
        "edit_note":"Edit note",
        "savebutton":"SAVE",
        "alertsmenu":"<i class=\"fas fa-exclamation-triangle\" ></i>Alerts",
        "usersmenu2":"<i class=\"fas fa-users\" ></i>Users",
        "estatisticasmenu2":"<i class=\"fas fa-chart-pie\"></i>Statistics",
        "search_passwords":"Searching passwords",
        "strength":"Strength",
        "show":"Show",
        "copy":"Copy",
        "search_password":"Search password...",
        "alerts":"Alerts",
        "new_password":"New password",
        "username":"Username",
        "username_label":"Username (optional)",
        "ex_password_name":"Ex.: My password",
        "ex_username":"Ex.: username@email.com",
        "remove_passwords":"Remove passwords",
        "remove_documents":"Remove documents",
        "remove_documents_desc":"Do you really want to remove the selected documents?",
        "remove_passwords_desc":"Do you really want to remove the selected passwords?",
        "edit_password":"Edit password",
        "edit_document":"Edit document",
        "search_statistics":"Searching statistics...",
        "search_user":"Search user...",
        "general":"General",
        "statistics":"Statistics",
        "health":"Health",
        "total_passwords":"Total",
        "repeated_passwords":"Repeated passwords",
        "users_subscriptions":"Users/Subscriptions",
        "main_categories":"Main categories",
        "main_users":"Main users",
        "email":"Email",
        "permission":"Permission",
        "search_user":"Search user...",
        "users":"Users",
        "new_user":"New user",
        "ex_permission":"Ex.: ADMIN",
        "remove_users":"Remove users",
        "remove_users_desc":"Do you really want to remove the selected user?<label class=\"custom-control custom-checkbox\"><input id=\"checkbox\" onclick=\"transfer()\" type=\"checkbox\" class=\"custom-control-input\"><span id=\"checkboxlabel\" class=\"custom-control-label\">Transfer to:</span></label><div class=\"form-group\" style=\"margin-top: 20px;\"><select class=\"selectpicker\" id=\"usertransfer\" disabled=true placeholder=\"Ex.: USER\" style=\"color: #fff; background: #262628;\" required></select>",
        "edit_user":"Edit user",
        "share":"Share",
        "warning":"Warninig",
        "remove":"Remove",
        "warning_no_permission":"You don't have permissions to manage shared items.",
        "pixmenu":"<iconify-icon icon=\"fa6-brands:pix\" style=\"padding-right:10px;\"> </iconify-icon>Instant transfer codes",
        "search_pix":"Searching instant transfer codes",
        "pixs":"Instant transfer codes",
        "pix":"Instant transfer code",
        "new_pix":"Add instant transfer code",
        "description":"Description",
        "description_optional":"Description (Optional)",
        "ex_pix_name":"Ex.: John Mayer",
        "ex_pix_desc":"Ex.: 548.964.147-23",
        "ex_description":"Ex.: Friend from work",
        "remove_pix":"Remove instant transfer codes",
        "remove_pix_desc":"Do you really want to remove the selected codes?",
        "edit_pix":"Edit instant transfer code",
        "search_pix_s":"Search instant transfer code...",
        "search_pix_error":"Error while searching instant transfer codes. Update the page and try again. Code",
        "pixs":"Instant transfer codes",
        "update_pix":"Updating instant transfer code",
        "update_pix_error":"Error while updating code. Update the page and try again. Code",
        "add_pix":"Creating instant transfer code",
        "add_pix_error":"Error while creating code. Update the page and try again. Code",
        "remove_pixs":"Removing instant transfer codes",
        "remove_pixs_error":"Error while removing instant transfer codes. Update the page and try again. Code",
        "capital_letters": "Capital letters (A-Z)",
        "small_letters": "Small letters (a-z)",
        "numbers": "Numbers (1-9)",
        "special_char": "Special characters",
        "length": "Length",
        "documents":"Documents",
        "search_document":"Search document...",
        "expiration_date":"Expiration date",
        "identification_code":"Identification code",
        "new_document":"New document",
        "expiration_label":"Expiration date (optional)",
        "search_documents":"Searching documents",
        "ex_doc_name":"Ex.: Passport",
        "ex_doc_desc":"Ex.: 2841299245",
        "ex_doc_expiration":"Ex.: 10/2025",
        "add_document":"Creating document",
        "privacy":"Privacy policy",
        "privacy-href":"https://isenhas.com.br/privacy-en.html",
        "update_shared_password":"It is not allowed to transfer an item to or from a shared vault.",
        "security":"Security",
        "new1_title":"Featured on the  App Store",
        "business_free":"TEAMS",
        "prepare_sub5":"In addition to security, iSenhas guarantees convenience. If you lose access to your account or forget the Access password, there are recovery mechanisms and technical support to help you regain control, without the risk of losing the information.",
        "prepare_sub6":"The perfect balance between advanced protection and the peace of mind of knowing your passwords will always be available when you need them.",
        "recovery_title":"Extreme privacy enabled",
        "recovery_key":"Recovery key",
        "recovery_desc1":"1. Enter the Recovery key to decrypt the items.",
        "recovery_nomeedit":"Ex.: EWBW9D-APV01V-1LE2OF-COHNHR-0JMKSO-C7",
        "recovery_loadinglabel":"Verifying Recovery key...",
        "recovery_login_error":"Wrong Recovery key. Reload the page and try again",
        "feature_not_available_extreme":"This feature is under development for user with Extreme privacy enabled.",
        "wrong_recovery_key":"Wrong Recovery key",
        "prepare_sub7":"Additionally, iSenhas offers the Extreme Privacy option, a zero-knowledge architecture mode. In this configuration, items are encrypted with AES-256 GCM using the Recovery Key before being sent to the cloud backup. Not even the iSenhas team has access to the content.",
        "isenhas_title":"iSenhas | Password Manager | Featured App Store"
    }
    var pt = 
    {
        "isenhas_title":"iSenhas | Gerenciador de senhas | Destaque App Store",
        "prepare_sub7":" Além disso, o iSenhas oferece a opção de Privacidade extrema, um modo de arquitetura de conhecimento zero. Nessa configuração, os itens são criptografados com AES-256 GCM usando a Chave de recuperação antes de serem enviados ao backup em nuvem. Nem mesmo a equipe do iSenhas tem acesso ao conteúdo.",
        "wrong_recovery_key":"Chave de recuperação inválida",
        "feature_not_available_extreme":"Essa funcionalidade está em desenvolvimento para usuários com Privacidade extrema habilitada.",
        "recovery_login_error":"Chave de recuperação incorreta. Atualize a página e tente novamente.",
        "recovery_loadinglabel":"Verificando chave de recuperação...",
        "recovery_nomeedit":"Ex.: EWBW9D-APV01V-1LE2OF-COHNHR-0JMKSO-C7",
        "recovery_desc1":"1. Digite a Chave de recuperação para descriptografar os itens.",
        "recovery_key":"Chave de recuperação",
        "recovery_title":"Privacidade extrema habilitada",
        "business_free":"EQUIPES",
        "new1_title":"Destaque na  App Store",
        "update_shared_password":"Não é permitido transferir um item de ou para um cofre compartilhado.",
        "search_vaults":"Buscando cofres",
        "personal":"Pessoal",
        "vault":"Cofre",
        "passkeys":"Chaves-senha",
        "privacy":"Política de privacidade",
        "add_document":"Criando documento",
        "ex_doc_expiration":"Ex.: 10/2025",
        "ex_doc_desc":"Ex.: 245.567.147-52",
        "ex_doc_name":"Ex.: CPF",
        "search_documents":"Buscando documentos",
        "expiration_label":"Expira em (opcional)",
        "new_document":"Novo documento",
        "identification_code":"Código de identificação",
        "expiration_date":"Expira em",
        "search_document":"Buscar documento...",
        "documents":"Documentos",
        "pixs":"Pix",
        "docsmenu":"<i class=\"fa fa-id-card\" ></i>Documentos",
        "isenhas":"iSenhas",
        "description_label":"Anotação (opcional)",
        "description_title":"Anotação",
        "favorite_pix":"Chave Pix favorita",
        "favorite_note":"Nota favorita",
        "favorite_password":"Senha favorita",
        "favorite_document":"Documento favorito",
        "capital_letters": "Maiúsculas (A-Z)",
        "small_letters": "Minúsculas (a-z)",
        "numbers": "Números (1-9)",
        "special_char": "Caracteres especiais",
        "length": "Comprimento",
        "remove_pixs":"Excluindo chaves Pix",
        "remove_pixs_error":"Erro ao excluir chaves Pix. Atualize a página e tente novamente. Código",
        "add_pix_error":"Erro ao adicionar chave Pix. Atualize a página e tente novamente. Código",
        "add_pix":"Adicionando chave Pix",
        "update_pix":"Atualizando chave Pix",
        "update_pix_error":"Erro ao atualizar chave Pix. Atualize a página e tente novamente. Código",
        "pixs":"Chaves Pix",
        "search_pix_error":"Erro ao buscar chaves Pix. Atualize a página e tente novamente. Código",
        "edit_pix":"Editar chave Pix",
        "remove_pix":"Excluir chaves Pix",
        "remove_pix_desc":"Você realmente gostaria de remover as chaves Pix selecionadas?",
        "ex_description":"Ex.: Amiga do trabalho",
        "ex_pix_desc":"Ex.: 548.964.147-23",
        "ex_pix_name":"Ex.: Ana Luísa",
        "description":"Descrição",
        "description_optional":"Descrição (Opcional)",
        "new_pix":"Adicionar chave Pix",
        "pix":"Chave Pix",
        "search_pix":"Buscando chaves Pix",
        "search_pix_s":"Buscar chave Pix...",
        "pixmenu":"<iconify-icon icon=\"fa6-brands:pix\" style=\"padding-right:10px;\"> </iconify-icon>Chaves Pix",
        "warning_no_permission":"Você não tem permissão para modificar itens compartilhadas.",
        "remove":"Excluir",
        "warning":"Atenção",
        "share":"Compartilhar",
        "edit_user":"Editar usuário",
        "remove_users_desc":"Você realmente gostaria de excluir o usuário selecionado?<label class=\"custom-control custom-checkbox\"><input id=\"checkbox\" onclick=\"transfer()\" type=\"checkbox\" class=\"custom-control-input\"><span id=\"checkboxlabel\" class=\"custom-control-label\">Transferir senhas para:</span></label><div class=\"form-group\" style=\"margin-top: 20px;\"><select class=\"selectpicker\" id=\"usertransfer\" disabled=true placeholder=\"Ex.: USER\" style=\"color: #fff; background: #262628;\" required></select>",
        "remove_users":"Excluir usuários",
        "ex_permission":"Ex.: ADMIN",
        "new_user":"Adicionar usuário",
        "Users":"Usuários",
        "search_user":"Buscar usuário...",
        "permission":"Permissão",
        "email":"Email",
        "main_users":"Principais usuários",
        "main_categories":"Principais categorias",
        "users_subscriptions":"Usuários/Assinaturas",
        "repeated_passwords":"Senhas repetidas",
        "total_passwords":"Total",
        "health":"Saúde",
        "statistics":"Estatísticas",
        "general":"Geral",
        "search_user":"Buscar usuário...",
        "search_statistics":"Buscando estatísticas...",
        "edit_password":"Editar senha",
        "edit_document":"Editar documento",
        "remove_passwords_desc":"Você realmente gostaria de excluir as senhas selecionadas?",
        "remove_documents":"Excluir documentos",
        "remove_documents_desc":"Você realmente gostaria de excluir os documentos selecionados?",
        "remove_passwords":"Excluir senhas",
        "ex_username":"Ex.: usuario@email.com",
        "ex_password_name":"Ex.: Minha senha",
        "username":"Usuário",
        "username_label":"Usuário (opcional)",
        "new_password":"Adicionar senha",
        "alerts":"Alertas",
        "search_password":"Buscar senha...",
        "copy":"Copiar",
        "show":"Mostrar",
        "strength":"Força",
        "search_passwords":"Buscando senhas...",
        "estatisticasmenu2":"<i class=\"fas fa-chart-pie\"></i>Estatísticas",
        "alertsmenu":"<i class=\"fas fa-exclamation-triangle\" ></i>Alertas",
        "usersmenu2":"<i class=\"fas fa-users\" ></i>Usuários",
        "savebutton":"SALVAR",
        "edit_note":"Editar nota",
        "remove_notes_desc":"Você realmente gostaria de excluir as notas selecionadas?",
        "remove_notes":"Excluir notas",
        "cancelbutton":"CANCELAR",
        "ex_note_desc":"Ex.: fea8hjaejJ(U",
        "ex_note":"Ex.: Minha nota",
        "note":"Nota",
        "new_note":"Adicionar nota",
        "buttonremove":"EXCLUIR",
        "buttonadd":"ADICIONAR",
        "notes":"Notas",
        "logoutmenu":"<i class=\"fas fa-sign-out-alt\" ></i>Sair",
        "notesmenu":"<i class=\"fas fa-sticky-note\" ></i>Notas",
        "passwordsmenu":"<i class=\"fas fa-key\" ></i>Senhas",
        "edit":"Editar",
        "note_search":"Buscar nota...",
        "copy":"Copiar",
        "password":"Senha",
        "name":"Nome",
        "notas_loading":"Buscando notas..",
        "login_checkbox":"Manter-me conectado",
        "login_loading":"Buscando usuário e preparando um ambiente seguro...",
        "btn_login":"ENTRAR",
        "login_desc2":"2. Clique no botão <b>ENTRAR</b> para acessar o iSenhas WEB.</h3>",
        "login_desc1":"1. Abra o aplicativo <b>iSenhas</b>, toque no botão<img style=\"height:30px;width: 30px;margin-left: 5px;margin-right: 5px;margin-bottom: 5px;\" alt=\"Qries\" src=\"/images/iconsmart/readbutton.png\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@fat\"/>e leia o <b>QRCode</b> acima (disponível para usuários Premium).</h3>",
        "login_title":"iSenhas WEB",
        "passwords":"Senhas",
        "sending_notifications":"Enviando notificações",
        "plan3_arg5":"<b>Compartilhamento</b> de senhas entre usuários.",
        "share":"Compartilhar",
        "shared_by" : "Compartilhado por",
        "strong_password":"Fortes",
        "regular_password":"Regulares",
        "weak_password":"Fracas",
        "bank":"Bancos e investimentos",
        "gov":"Governo",
        "market":"Comércio",
        "travel":"Viagens",
        "document":"Documentos",
        "internet":"Telefonia e internet",
        "website":"Websites e apps",
        "access":"Acessos",
        "magazine":"Jornais e revistas",
        "other":"Outras",
        "notes":"Notas",
        "search_statistics":"Buscando estatísticas. Isso pode demorar um pouco",
        "add_user_already_exists":"Este usuário já existe. Erro",
        "add_user_limit":"O limite de usuários foi atingido. Por favor, entre em contato com o time de vendas do iSenhas para fazer um upgrade do seu plano Business.",
        "users":"Usuários",
        "plan3_arg1":"<b>Compartilhamento de senhas</b> em cofres.",
        "plan3_arg2":"Gestão de <b>perfis</b> de usuário.",
        "plan3_arg3":"Dashboard para <b>gerenciamento de alertas</b>.",
        "plan3_arg4":"Transferência de senhas <b>ao excluir usuário</b>.",
        "plan3_arg6":"Suporte 24/7 em português.",
        "business_get":"BAIXAR APP",
        "business_month":"cada usuário/mês",
        "business_price":"R$ 5,90",
        "business_download":"BAIXAR PDF",
        "googlesafe":"/images/googlesafe.png",
        "popularapps":"/images/popularapps_pt.png",
        "appswelove":"/images/appswelove_pt.png",
        "apple_ecamp":"/images/apple_ecamp_pt.png",
        "appswelove_link":"https://www.instagram.com/p/DEK9ubfOEXD/?img_index=1",
        "popularapps_link":"https://www.instagram.com/p/DEK9ubfOEXD/?img_index=5",
        "img1":"/images/senha.webp",
        "img2":"/images/pastas.webp",
        "img3":"/images/alertas.webp",
        "img4":"/images/web.webp",
        "img5":"/images/chrome.webp",
        "img6":"/images/login.webp",
        "contact_ok":"Obrigado por sua mensagem. Entraremos em contato o mais rápido possível.",
        "contact_name":"Nome completo*",
        "contact_email":"Email*",
        "contact_text":"Escreva para nós aqui! Para agilizar o atendimento, informe o seu sistema operacional (iOS ou Android).",
        "contact_send":"ENVIAR",
        "contact_title":"Fale conosco",
        "contact_sub":"Sentiu falta de alguma coisa ou encontrou algum problema? Escreva para nós ou entre em contato pelo<br><b>Whatsapp (47) 99200-2269</b>. Responderemos o mais rápido possível.",
        "new3_title":"Quem faz o iSenhas?",
        "new3_sub1":"Davi Orzechowski",
        "new3_sub2":"Fundador",
        "new3_desc":"Quer saber um pouco mais da história do iSenhas? Veja esse vídeo que conta o início de nossa trajetória.",
        "new2_desc":"Veja como é fácil e seguro usar o iSenhas no computador. Utilize as extensões para navegador ou plataforma WEB.",
        "new2_sub2":"Tutorial",
        "new2_sub1":"Videos",
        "new2_title":"Como usar o iSenhas no computador?",
        "know_more":"SAIBA MAIS",
        "achievements":"Conquistas",
        "achievements_sub":"O iSenhas foi destacado pela Apple na lista \"Apps populares\".",
        "news_sub":"Fique por dentro do que estamos trabalhando,<br>novas funcionalidades e conquistas.",
        "news_title":"Últimas notícias",
        "plan2_arg1":"Armazenamento <b>ilimitado em cloud</b>.",
        "plan2_arg2":"<b>Todas as funções</b> do plano gratuito.",
        "plan2_arg3":"Verificação <b>ilimitada</b> de vazamentos na Dark Web.",
        "plan2_arg4":"Armazenamento das senhas <b>em cloud</b>.",
        "plan2_arg5":"Lista com alertas de segurança.",
        "plan2_arg6":"Autocompletar formulários.",
        "plan2_arg7":"Compartilhamento <b>seguro</b> de senhas.",
        "plan2_arg8":"Acesso às senhas em <b>qualquer dispositivo</b>.",
        "plan2_arg9":"<b>Recuperação</b> de senhas.",
        "premium_price":"R$ 7,90",
        "plan1_arg1":"Armazenamento <b>local</b> de até 5 senhas.",
        "plan1_arg2":"<b>Algoritmo</b> de organização em pastas.",
        "plan1_arg3":"Detecção <b>automática</b> de ícones.",
        "plan1_arg4":"<b>Gerador</b> de senhas.",
        "plan1_arg5":"Lista com <b>alertas</b> de segurança.",
        "plan1_arg6":"<b>Autocompletar</b> formulários.",
        "plan1_arg7":"3 verificações de <b>vazamentos na Dark Web</b>.",
        "plans_get":"BAIXAR APP",
        "plans_free":"GRATUITO",
        "plans_price":"R$ 0,00",
        "plans_month":"Por mês",
        "plans_title":"Planos",
        "plans_sub":"Confira os planos disponíveis dentro do Google Play e App Store.<br>Você poderá adquiri-los através dos aplicativos.",
        "fast_support":"Suporte rápido",
        "cups_coffe":"Canecas de café",
        "top_appstore":"Top App Store Brasil",
        "happy_customers":"Clientes felizes",
        "years_appstore":"Anos na App Store",
        "questions4_answer":"Sim. Você também pode armazenar notas e lembretes de forma segura.",
        "questions4":"Posso armazenar mais algo além de senhas?",
        "questions3_answer":"Compatibilidade: Os programas de gerenciadores de senhas, são multiplataformas e multi-navegadores. Já os gerenciadores de senhas dos navegadores não: eles estão limitados àquele navegador específico.<br>Gerador de senhas: O maior inimigo de suas contas online é a reutilização de senhas. Caso você faça isso, e a senha seja descoberta, todas as outras contas estarão expostas. Assim, será muito fácil para o invasor hackear suas contas - atualmente esse truque é o mais comum.",
        "questions3":"Por que usar o iSenhas ao invés do gerenciador de senhas do navegador de internet?",
        "questions2":"Consigo recuperar minhas senhas se perder o celular?",
        "questions2_answer":"Sim. Este é um benefício do plano Premium. Você poderá recuperar as senhas a qualquer momento ao restaurar sua conta em outro smartphone.",
        "questions1_answer":"Não. Você é nosso cliente e não nosso produto. Suas senhas são protegidas para que ninguem além de você tenha acesso.",
        "questions1":"Alguém possui acesso as minhas senhas?",
        "questions_title":"Nossas respostas aos questionamentos mais comuns",
        "edge_title":"Extensão Edge",
        "edge_sub":"Ganhe produtividade no navegador oficial da Microsoft.",
        "chrome_title":"Extensão Chrome",
        "chrome_sub":"Aumente sua agilidade ao acessar sites com a extensão para o Chrome.",
        "brave_title":"Extensão Brave",
        "brave_sub":"Aumente sua segurança ao acessar sites com a extensão para o Brave.",
        "firefox_title":"Extensão Firefox",
        "firefox_sub":"Gerencie e complete formulários no Firefox.",
        "safari_title":"Extensão Safari",
        "safari_sub":"Utilize o iSenhas no navegador oficial da Apple.",
        "android_title":"Aplicativo Android",
        "android_sub":"Baixe suas senhas em tables e smartphones Android.",
        "ios_title":"Aplicativo iOS/MacOS",
        "ios_sub":"Baixe o app que é top 100 mais baixados na App Store.",
        "download_title":"Baixar",
        "download_sub":"Clique em uma das opções para ser direcionado a loja de cada uma das soluções.<br>O iSenhas não é fornecido fora de lojas oficiais.",

        "android_user":"Usuário Android",
        "ios_user":"Usuário iOS",
        "review1":"Ótimo e descomplicado aplicativo. Atende perfeitamente. Recomendo. Parabéns ao desenvolvedor.",
        "review2":"Aplicativo super funcional e prático de utilizar, guardava minhas senhas no bloco de notas, sem muita privacidade, com o App ficou bem mais seguro.",
        "review3":"App bem intuitivo, cumpre o que promete. Consigo gravar todas minha senhas com segurança.",
        "davi_title":"Fundador",
        "davi_sub":"O Davi é engenheiro e criador do iSenhas.<p>Com mais de 10 anos de experiência, já passou por multinacionais e ganhou prêmios de inovação durante sua carreira.",
        "lisi_title":"Administradora e Contadora",
        "lisi_sub":"Graduada em Administração e Contabilidade ela direciona o iSenhas no caminho de manter-se uma ferramenta simples e útil. Experiente na indústria, traça o planejamento estratégico e marketing do produto.",
        "us_title" : "Conheça o fundador",
        "us_sub":"A mente por trás do iSenhas e da ideia de segurança sem complicação.",
        "explore_sub":"Veja os detalhes que preparamos em cada tela com o intuito de<br>transformar sua experiência com senhas.",
        "explore_title":"Explore a solução",
        "get_app":"BAIXAR",
        "prepare_sub1":"O iSenhas nunca sofreu violação. Mas, caso ocorra, ela não colocará os dados confidenciais do seu cofre em risco.",
        "prepare_sub2":"Cada item é protegido com uma chave de criptografia AES-256 antes de ser armazenado no backup em nuvem do iSenhas, localizado no Google Cloud.",
        "prepare_sub4":"Para o armazenamento offline, no próprio dispositivo, o iSenhas utiliza derivação da Chave de acesso PBKDF2 para criptografar os itens com AES-256 GCM, garantindo a máxima proteção mesmo sem conexão com a internet.",
        "prepare_sub8":"O iSenhas também valoriza a transparência. Parte do código-fonte é público e pode ser acessado no GitHub, permitindo que a comunidade analise, audite e acompanhe a evolução da segurança do projeto.",
        "prepare_sub5":"Segurança e praticidade. Ao perder o acesso à conta ou esquecer a Chave de acesso existem mecanismos de recuperação e suporte técnico para ajudar a retomar o controle, sem o risco de perder as informações.",
        "prepare_sub6":"Assim, o iSenhas oferece o equilíbrio perfeito entre proteção avançada e a tranquilidade de saber que as senhas estarão sempre disponíveis quando precisar.",
        "prepare_desc":"Segurança avançada.",
        "prepare_title":"O iSenhas é seguro?",
        "how_works_scan":"Examinar",
        "how_works_scan_sub":"Verifique a saúde de suas senhas na lista de alertas e tome ações para melhorar sua segurança.",
        "how_works_autofill":"Autocompletar",
        "how_works_autofill_sub":"Preencha campos de login de forma ágil em qualquer dispositivo.",
        "how_works_generate":"Gerar",
        "how_works_generate_sub":"Gere senhas fortes de até 30 dígitos com caracteres especiais, maiúsculas e números.",
        "how_works_import_sub":"Importe suas senhas do Google, LastPass, Dashlane, Bitwarden, SafeInCloud ou de Arquivos customizados.",
        "how_works_import" :"Importar",
        "how_works_sub":"Configuração rápida e simples para acessar suas senhas de qualquer dispositivo <br>com sensor Biométrico ou sua Senha única.",
        "how_works" :"Como funciona?",
        "title_sub1":"Acesse senhas de qualquer lugar através de aplicativos, website ou extensão para navegador.",
        "title_sub2":"Utilize o algoritmo inteligente de organização em pastas e detecção automática de ícones.",
        "title_sub3":"Crie senhas fortes e aleatórias em ambiente com criptografia AES-256 e seguro.",
        "title_start":"Gerencie senhas com segurança e inteligência.",
        "my_passwords":"MINHAS SENHAS",
        "contact":"CONTATO",
        "price":"PLANOS",
        "download":"BAIXAR",
        "team":"EQUIPE",
        "gallery":"GALERIA",
        "about":"SOBRE",
        "search_notes":"Buscando notas",
        "search_statistics_error":"Erro ao buscar estatísticas. Atualize a página e tente novamente. Código",
        "search_notes_error":"Erro ao buscar notas. Atualize a página e tente novamente. Código",
        "add_note":"Adicionando nota",
        "add_note_error":"Erro ao adicionar nota. Atualize a página e tente novamente. Código",
        "add_user":"Adicionando usuário",
        "add_user_error":"Erro ao adicionar usuário. Atualize a página e tente novamente. Código",
        "no_selection":"Nenhuma nota selecionada.",
        "remove_note":"Excluindo notas",
        "remove_note_error":"Erro ao excluir notas. Atualize a página e tente novamente. Código",
        "remove_user":"Excluindo usuário",
        "remove_user_error":"Erro ao excluir usuário. Atualize a página e tente novamente. Código",
        "update_note":"Atualizando nota",
        "update_note_error":"Erro ao atualizar nota. Atualize a página e tente novamente. Código",
        "search_passwords":"Buscando senhas",
        "search_users":"Buscando usuários",
        "search_users_error":"Erro ao buscar usuários. Atualize a página e tente novamente. Código",
        "search_passwords_error":"Erro ao buscar senhas. Atualize a página e tente novamente. Código",
        "add_password":"Adicionando senha",
        "add_password_error":"Erro ao adicionar senha. Atualize a página e tente novamente. Código",
        "no_password_selected":"Nenhuma senha selecionada.",
        "no_user_selected":"Nenhum usuário selecionado.",
        "remove_password":"Excluindo senhas",
        "remove_document":"Excluindo documentos",
        "remove_password_error":"Erro ao excluir senhas. Atualize a página e tente novamente. Código",
        "update_password":"Atualizando senha",
        "update_document":"Atualizando documento",
        "update_password_error":"Erro ao atualizar senha. Atualize a página e tente novamente. Código",
        "update_user":"Atualizando usuário",
        "update_user_error":"Erro ao atualizar usuário. Atualize a página e tente novamente. Código",
        "code_notfound":"Código não encontrado. Atualize a página e tente novamente.",
        "login_error":"Erro ao autenticar usuário. Atualize a página e tente novamente. Código",
        "weak":"Fraca",
        "very_weak":"Muito fraca",
        "regular":"Razoável",
        "strong":"Forte",
        "very_strong":"Muito forte",
        "home":"Início",
        "repeated":"Repetida",
        "social":"Encontre-nos nas redes sociais:",
        "privacy-href":"https://isenhas.com.br/privacy.html",
        "security":"Segurança"
    }
    var es = 
    {
        "isenhas_title":"iSenhas | Administrador de contraseñas | Destacado App Store",
        "prepare_sub7":"Además, iSenhas ofrece la opción de Privacidad Extrema, un modo de arquitectura de conocimiento cero. En esta configuración, los elementos se cifran con AES-256 GCM mediante la clave de recuperación antes de enviarse a la copia de seguridad en la nube. Ni siquiera el equipo de iSenhas tiene acceso al contenido.",
        "wrong_recovery_key": "Clave de recuperación no válida",
        "feature_not_available_extreme": "Esta función está en desarrollo para usuarios con privacidad extrema habilitada.",
        "recovery_login_error": "Clave de recuperación incorrecta. Actualice la página y vuelva a intentarlo.",
        "recovery_loadinglabel": "Verificando Clave de recuperación...",
        "recovery_nomeedit":"Ej.: EWBW9D-APV01V-1LE2OF-COHNHR-0JMKSO-C7",
        "recovery_desc1": "1. Ingrese la clave de recuperación para descifrar los elementos",
        "recovery_key": "Clave de recuperación",
        "recovery_title":"Privacidad extrema habilitada",
        "prepare_sub5": "Además de la seguridad, iSenhas garantiza comodidad. Si pierde el acceso a su cuenta u olvida su contraseña, existen mecanismos de recuperación y soporte técnico para ayudarle a recuperar el control, sin el riesgo de perder su información.",
        "prepare_sub6": "El equilibrio perfecto entre protección avanzada y la tranquilidad de saber que sus contraseñas siempre estarán disponibles cuando las necesite.",
        "business_free":"EQUIPOS",
        "update_shared_password":"No es posible transferir un artículo hacia o desde una bóveda compartida.",
        "search_vaults":"Buscando bóvedas",
        "personal":"Personal",
        "vault":"Bóveda",
        "passkeys":"Claves de acceso",
        "privacy-href":"https://isenhas.com.br/privacy-en.html",
        "privacy": "Política de privacidad",
        "add_document":"Creando documento",
        "ex_doc_expiration":"Ex.: 10/2025",
        "ex_doc_desc":"Ej.: 56892689186",
        "ex_doc_name":"Ej.: Pasaporte",
        "search_documents":"Buscando documentos",
        "expiration_label":"Expira en (opcional)",
        "new_document":"Nuevo documento",
        "identification_code":"Código de identificación",
        "expiration_date": "Expira el",
        "search_document":"Buscar documento...",
        "documents":"Documentos",
        "pixs":"Códigos de transferencia instantánea",
        "docsmenu":"<i class=\"fa fa-id-card\" ></i>Documentos",
        "isenhas":"iSenhas",
        "description_label":"Anotación (opcional)",
        "description_title":"Anotación",
        "favorite_pix":"Código de transferencia favorito",
        "favorite_note":"Nota favorita",
        "favorite_document":"Documento favorito",
        "favorite_password":"Contraseña favorita",
        "capital_letters": "Letras mayúsculas (A-Z)",
        "small_letters": "Letras minúsculas (a-z)",
        "numbers": "Números (1-9)",
        "special_char": "Caracteres especiales",
        "length": "Longitud",
        "update_pix":"Actualizando código de transferencia instantánea",
        "update_pix_error":"Error al actualizar la código de transferencia instantánea. Actualiza la página e inténtalo de nuevo. Código",
        "remove_pixs":"Eliminando codigo de transferencia instantanea",
        "remove_pixs_error":"Error al eliminar codigo de transferencia instantanea. Actualiza la página e inténtalo de nuevo. Código",
        "add_pix":"Creando codigo de transferencia instantanea",
        "add_pix_error":"Error al crear el codigo de transferencia instantanea. Actualiza la página e inténtalo de nuevo. Código",
        "description_optional":"Descripción (Opcional)",
        "pixs":"Códigos de transferencia instantánea",
        "search_pix_error":"Error al buscar códigos de transferencia instantánea. Actualiza la página e inténtalo de nuevo. Código",
        "edit_pix":"Editar código de transferencia instantánea",
        "remove_pix":"Eliminar códigos de transferencia instantánea",
        "remove_pix_desc":"¿Realmente desea eliminar los códigos seleccionados?",
        "ex_description": "Ej .: Amiga del trabajo",
        "ex_pix_desc":"Ej.: 548.964.147-23",
        "ex_pix_name":"Ej.: John Mayer",
        "description":"Descripción",
        "new_pix":"Agregar codigo de transferencia instantanea",
        "pix":"Código de transferencia instantánea",
        "search_pix":"Buscando códigos de transferencia instantánea",
        "search_pix_s":"Buscar código de transferencia instantánea...",
        "pixmenu":"<iconify-icon icon=\"fa6-brands:pix\" style=\"padding-right:10px;\"> </iconify-icon>Códigos",
        "search_notes":"Buscando notas",
        "search_notes_error":"Error al buscar notas. Actualiza la página e inténtalo de nuevo. Código",
        "search_statistics_error":"Error al buscar estadísticas. Actualiza la página e inténtalo de nuevo. Código",
        "add_note":"Creando nota",
        "add_note_error":"Error al crear la nota. Actualiza la página e inténtalo de nuevo. Código",
        "add_user":"Creando usuario",
        "add_user_error":"Error al crear el usuario. Actualiza la página e inténtalo de nuevo. Código",
        "no_selection":"Ninguna nota seleccionada.",
        "remove_note":"Eliminando notas",
        "remove_note_error":"Error al eliminar notas. Actualiza la página e inténtalo de nuevo. Código",
        "remove_user":"Eliminando usuario",
        "remove_user_error":"Error al eliminar al usuario. Actualiza la página e inténtalo de nuevo. Código",
        "update_note":"Actualizando nota",
        "update_note_error":"Error al actualizar la nota. Actualiza la página e inténtalo de nuevo. Código",
        "update_user":"Actualizando usuario",
        "update_user_error":"Error al actualizar el usuario. Actualiza la página e inténtalo de nuevo. Código",
        "search_passwords":"Buscando contraseñas",
        "search_passwords_error":"Error al buscar contraseñas. Actualiza la página e inténtalo de nuevo. Código",
        "search_users":"Buscando usuarios",
        "search_users_error":"Error al buscar usuarios. Actualiza la página e inténtalo de nuevo. Código",
        "add_password":"Creando contraseña",
        "add_password_error":"Error al crear la contraseña. Actualiza la página e inténtalo de nuevo. Código",
        "no_password_selected":"Sin contraseña seleccionada",
        "no_user_selected":"Ningún usuario seleccionado",
        "remove_password":"Eliminando contraseñas",
        "remove_document":"Eliminando documentos",
        "remove_password_error":"Error al eliminar contraseñas. Actualiza la página e inténtalo de nuevo. Código",
        "update_password":"Actualizando contraseña",
        "update_document":"Actualizando documento",
        "update_password_error":"Error al actualizar la contraseña. Actualiza la página e inténtalo de nuevo. Código",
        "code_notfound":"Código no encontrado. Actualiza la página y vuelve a intentarlo.",
        "login_error":"Error durante la autenticación. Actualiza la página e inténtalo de nuevo. Código",
        "weak":"Débil",
        "very_weak":"Muy débil",
        "regular":"Regular",
        "strong":"Fuerte",
        "very_strong":"Muy fuerte",
        "home":"Inicio",
        "repeated":"Repetido",
        "about":"SOBRE",
        "gallery":"GALERIA",
        "team" : "EQUIPO",
        "download":"DESCARGAR",
        "price":"PLANES",
        "contact":"CONTACTO",
        "my_passwords":"INICIAR",
        "title_start":"¿Quieres administrar contraseñas con inteligencia y seguridad?",
        "title_sub1":"Acceda a sus contraseñas desde cualquier lugar a través de aplicaciones, sitio web o extensión del navegador.",
        "title_sub2":"Use nuestro algoritmo inteligente de clasificación de carpetas y detección automática de íconos.",
        "title_sub3":"Cree contraseñas seguras y aleatorias en nuestro entorno seguro y encriptado.",
        "how_works" :"¿Cómo funciona?",
        "how_works_sub":"Configuración rápida y sencilla para acceder a sus contraseñas desde cualquier dispositivo con <br>sensor biométrico o su contraseña única.",
        "how_works_import":"Importar",
        "how_works_import_sub":"Importa tus contraseñas de Google, LastPass, Dashlane, Bitwarden, SafeInCloud o Custom Files.",
        "how_works_generate":"Generar",
        "how_works_generate_sub":"Genera contraseñas seguras de hasta 30 dígitos con caracteres especiales, letras mayúsculas y números.",
        "how_works_autofill":"Autocompletar",
        "how_works_autofill_sub":"Rellene los campos de inicio de sesión rápidamente en cualquier dispositivo.",
        "how_works_scan":"Escanear",
        "how_works_scan_sub":"Verifique el estado de sus contraseñas en la lista de alertas y tome medidas para mejorar su seguridad.",
        "prepare_sub1": "iSenhas nunca ha sufrido una violación. Pero, si llegara a ocurrir, no pondría en riesgo los datos confidenciales de tu bóveda.",
        "prepare_sub2": "Cada ítem está protegido con una clave de cifrado AES-256 antes de ser almacenado en la copia de seguridad en la nube de iSenhas.",
        "prepare_sub4": "Para el almacenamiento fuera de línea en el propio dispositivo, iSenhas utiliza una derivación PBKDF2 de la contraseña de acceso para cifrar los elementos con AES-256 GCM, lo que garantiza la máxima protección incluso sin una conexión a Internet.",
        "prepare_sub8": "iSenhas también valora la transparencia. Parte del código fuente es público y se puede acceder a él en GitHub, lo que permite a la comunidad analizar, auditar y supervisar la evolución de la seguridad del proyecto",
        "prepare_desc": "Seguridad avanzada.",
        "prepare_title": "¿iSenhas es seguro?",
        "get_app":"OBTENER",
        "explore_title":"Explora la solución",
        "explore_sub":"Vea los detalles que hemos preparado en cada pantalla para<br>transformar su experiencia de contraseña.",
        "us_title": "Conozca al fundador",
        "us_sub":"La mente detrás de iSenhas y la idea de una seguridad sin complicaciones.",
        "davi_title":"Desarrollador de software",
        "davi_sub":"Davi es el fundador y principal desarrollador de iSenhas. Con más de 10 años de experiencia, ha trabajado para multinacionales y ganado premios a la innovación durante su carrera.",
        "lisi_title":"Gerente y Contador",
        "lisi_sub":"Graduada en Administración y Contabilidad, dirige iSenhas en el camino de seguir siendo una herramienta sencilla y útil. Con experiencia en la industria, perfila la planificación estratégica y la comercialización del producto.",
        "review1":"Excelente y sencilla aplicación. Te sirve perfectamente. La recomiendo. Felicitaciones al desarrollador.",
        "review2":"Aplicacion super funcional y practica de usar, guardaba mis contraseñas en la libreta, sin mucha privacidad, con la App era mucho mas seguro.",
        "review3":"Aplicación muy intuitiva, cumple lo que promete. Puedo registrar todas mis contraseñas de forma segura.",
        "android_user":"Usuario de Android",
        "ios_user":"Usuario de iOS",
        "download_title":"Descargar",
        "download_sub":"Haga clic en una de las opciones para ser dirigido a la tienda de cada solución.<br>iSenhas no se proporciona fuera de las tiendas oficiales.",
        "ios_title":"Aplicación de iOS/MacOS",
        "ios_sub":"Descarga la aplicación que está entre las 100 más descargadas en la App Store de Brasil.",
        "android_title":"Aplicación de Android",
        "android_sub":"Descarga tus contraseñas en tabletas y teléfonos inteligentes Android.",
        "chrome_title":"Extensión de Chrome",
        "chrome_sub":"Aumenta tu velocidad al acceder a sitios web con la extensión de Chrome.",
        "brave_title":"Extensión de Brave",
        "brave_sub":"Aumenta tu seguridad al acceder a sitios web con la extensión Brave.",
        "edge_title":"Extensión de Edge",
        "edge_sub":"Gana productividad en el navegador oficial de Microsoft.",
        "firefox_title":"Extensión de Firefox",
        "firefox_sub":"Administrar y completar contraseñas en el navegador Firefox.",
        "safari_title":"Extensión de Safari",
        "safari_sub":"Usa iSenhas en el navegador oficial de Apple.",
        "questions_title":"Nuestras respuestas a las preguntas más comunes",
        "questions1":"¿Alguien tiene acceso a mis contraseñas?",
        "questions1_answer":"No. Usted es nuestro cliente y no nuestro producto. Sus contraseñas están protegidas para que nadie más que usted tenga acceso.",
        "questions2":"¿Alguien tiene acceso a mis contraseñas?",
        "questions2_answer":"No. Usted es nuestro cliente y no nuestro producto. Sus contraseñas están protegidas para que nadie más que usted tenga acceso.",
        "questions3_answer":"Compatibilidad: los programas de administración de contraseñas son multiplataforma y multinavegador. Los administradores de contraseñas de navegador no lo son: están limitados a ese navegador específico.<br>Generador de contraseñas: el mayor enemigo de sus cuentas en línea es la reutilización de contraseñas. Si haces eso, y la contraseña es descifrada, todas las demás cuentas quedarán expuestas. Por lo tanto, será muy fácil para el atacante piratear tus cuentas; actualmente, este truco es el más común.",
        "questions3":"¿Por qué usar iSenhas en lugar del administrador de contraseñas del navegador web?",
        "questions4_answer":"Sí. También puedes almacenar notas y recordatorios de forma segura.",
        "questions4":"¿Puedo almacenar algo más además de contraseñas?",
        "years_appstore":"Años en la App Store",
        "happy_customers":"Clientes felices",
        "top_appstore":"App Store Brasil",
        "cups_coffe":"Tazas de café",
        "fast_support":"Soporte rápido",
        "plans_title":"Planes",
        "plans_sub":"Consulta los planes disponibles en Google Play y App Store.<br>Podrás adquirirlos a través de las aplicaciones.",
        "plans_free":"GRATIS",
        "plans_price":"$ 0.00",
        "plans_month":"Por mes",
        "plans_get":"OBTENER",
        "plan1_arg1":"Almacenamiento <b>Local</b> de hasta 5 contraseñas.",
        "plan1_arg2":"Carpetas inteligentes <b>algoritmo</b>.",
        "plan1_arg3":"<b>Detección automática</b> de íconos.",
        "plan1_arg4":"Contraseña <b>generador</b>.",
        "plan1_arg5":"Lista con <b>alertas</b> de seguridad.",
        "plan1_arg6":"<b>Autocompletar</b> inicios de sesión de usuario.",
        "plan1_arg7":"3 escaneos de brechas en <b>Dark Web</b>.",
        "premium_price":"$0.99",
        "plan2_arg1":"Almacenamiento <b>ilimitado</b> en la nube.",
        "plan2_arg2":"<b>Todas</b> las funciones gratuitas del plan.",
        "plan2_arg3":"Análisis de infracciones de la Dark Web <b>ilimitadas</b>.",
        "plan2_arg4":"Contraseña de almacenamiento <b>en la nube<b/>.",
        "plan2_arg5":"Lista con alertas de seguridad.",
        "plan2_arg6":"Autocompletar inicios de sesión de usuario.",
        "plan2_arg7":"Compartir <b>contraseñas seguras</b>.",
        "plan2_arg8":"Accede a tus contraseñas en <b>cualquier dispositivo</b>.",
        "plan2_arg9":"Contraseñas <b>recuperación</b>.",
        "news_title":"Últimas noticias",
        "news_sub":"Mantente al tanto de lo que estamos trabajando,<br>nuevas características y logros.",
        "achievements":"Logros",
        "achievements_sub":"iSenhas fue incluida por Apple en la lista de aplicaciones populares.",
        "know_more":"SABER MAS",
        "new2_title":"¿Cómo usar iSenhas en la computadora?",
        "new1_title":"Destacado em la  App Store",
        "new2_sub1":"Vídeos",
        "new2_sub2":"Tutorial",
        "new2_desc":"Vea lo fácil y seguro que es usar iSenhas en su computadora.",
        "new3_title":"¿Quién hace los iSenhas?",
        "new3_sub1":"Davi Orzechowski",
        "new3_sub2":"Fundador",
        "new3_desc":"¿Quieres saber un poco más sobre la historia de iSenhas? Mira este video que cuenta el inicio de nuestra trayectoria.",
        "contact_title":"Hable con nosotros",
        "contact_sub":"¿Te perdiste algo o encontraste un problema? Escríbenos.<br>Te responderemos lo antes posible.",
        "contact_name":"Nombre completo*",
        "contact_email":"Correo electrónico*",
        "contact_text":"¡Escríbenos aquí! Para agilizar el servicio, informa tu sistema operativo (iOS o Android).",
        "contact_send":"ENVIAR",
        "contact_ok":"Gracias por su mensaje. Nos pondremos en contacto con usted lo antes posible.",
        "img1":"/images/senha-en.webp",
        "img2":"/images/pastas-en.webp",
        "img3":"/images/alertas-en.webp",
        "img4":"/images/web-en.webp",
        "img5":"/images/chrome-en.webp",
        "img6":"/images/login-en.webp",
        "googlesafe":"/images/googlesafe-en.png",
        "popularapps":"/images/popularapps.png",
        "appswelove":"/images/appswelove.png",
        "apple_ecamp":"/images/apple_ecamp.png",
        "appswelove_link":"https://www.instagram.com/p/C-3u1XjJeON/",
        "popularapps_link":"https://www.instagram.com/p/C92SvgRO3Ku/",
        "social":"Encuéntranos en las redes sociales:",
        "business_price":"$ 1.10",
        "business_month":"cada usuario/mes",
        "business_get":"OBTENER",
        "business_download":"DESCARGAR PDF",
        "plan3_arg6": "Soporte 24/7.",
        "plan3_arg1":"Características premium para <b>todos los usuarios</b>.",
        "plan3_arg2":"Administración de usuarios con <b>perfiles</b>.",
        "plan3_arg3":"Panel dedicado para la <b>administración</b> de contraseñas.",
        "plan3_arg4":"<b>Alerta</b> lista de seguridad.",
        "users":"Usuarios",
        "add_user_limit":"Se alcanzó el límite de usuarios. Por favor, comuníquese con el departamento de ventas de iSenhas para actualizar su plan Business.",
        "add_user_already_exists":"Este usuario ya existe. Error",
        "search_statistics":"Obteniendo estadísticas. Esto podría llevar un tiempo",
        "bank":"Bancos",
        "gov":"Gobierno",
        "market":"Mercado",
        "travel":"Viajar",
        "document":"Documentos",
        "internet":"Operadores",
        "website":"Sitios web | Aplicaciones",
        "access":"Acceso",
        "magazine":"Revistas",
        "other":"Otros",
        "notes":"Notas",
        "strong_password":"Fuerte",
        "regular_password":"Regular",
        "weak_password":"Débil",
        "shared_by" : "Compartido por",
        "share":"Compartir",
        "plan3_arg5": "<b>Compartir</b> contraseñas entre usuarios.",
        "sending_notifications":"Enviando notificaciones",
        "passwords":"Contraseñas",
        "login_title":"iSenhas WEB",
        "login_desc1":"1. Abra la aplicación <b>iSenhas</b>toca el botón<img style=\"height:30px;width: 30px;margin-left: 5px;margin-right: 5px;margin-bottom: 5px;\" alt=\"Qries\" src=\"/images/iconsmart/readbutton.png\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@fat\"/>y autentíquese con el <b>QRCode</b> anterior (disponible para usuarios Premium).</h3>",
        "login_desc2":"2. Haga clic en <b>INICIAR</b> para acceder a iSenhas WEB.",
        "btn_login":"INICIAR",
        "login_loading":"Buscando usuarios y preparando un entorno seguro...",
        "login_checkbox":"Mantenerme conectado",
        "notas_loading":"Buscando notas..",
        "name":"Nombre",
        "password":"Contraseña",
        "copy":"Copiar",
        "note_search":"Buscar nota...",
        "edit":"Editar",
        "passwordsmenu":"<i class=\"fas fa-key\" ></i>Contraseñas",
        "notesmenu":"<i class=\"fas fa-sticky-note\" ></i>Notas",
        "logoutmenu":"<i class=\"fas fa-sign-out-alt\" ></i>Cerrar sesión",
        "notes":"Notas",
        "buttonadd":"AGREGAR",
        "buttonremove":"ELIMINAR",
        "new_note":"Nueva nota",
        "note":"Nota",
        "ex_note":"Ej.: Mi nota",
        "ex_note_desc":"Ej.: fea8hjaejJ(U",
        "cancelbutton":"CANCELAR",
        "remove_notes":"Eliminar notas",
        "remove_notes_desc":"¿Realmente quieres eliminar las notas seleccionadas?",
        "edit_note":"Editar nota",
        "savebutton":"GUARDAR",
        "alertsmenu":"<i class=\"fas fa-exclamation-triangle\" ></i>Alertas",
        "usersmenu2":"<i class=\"fas fa-users\" ></i>Usuarios",
        "estatisticasmenu2":"<i class=\"fas fas fa-chart-pie\"></i>Estadísticas ",
        "search_passwords":"Buscando contraseñas",
        "strength":"Fuerza",
        "show":"Show",
        "copy":"Copiar",
        "search_password":"Buscar contraseña...",
        "alerts":"Alertas",
        "new_password":"Nueva contraseña",
        "username":"Nombre de usuario",
        "username_label":"Nombre de usuario (opcional)",
        "ex_password_name":"Ej.: Mi contraseña",
        "ex_username":"Ej.: nombredeusuario@email.com",
        "remove_passwords":"Eliminar contraseñas",
        "remove_passwords_desc":"¿Realmente desea eliminar las contraseñas seleccionadas?",
        "remove_documents":"Eliminar documentos",
        "remove_documents_desc":"¿Realmente desea eliminar los documentos seleccionados?",
        "edit_password":"Editar contraseña",
        "edit_document":"Editar documento",
        "search_statistics":"Buscando estadísticas...",
        "search_user":"Buscar usuario...",
        "general":"General",
        "statistics":"Estadísticas",
        "health":"Estado",
        "total_passwords":"Total",
        "repeated_passwords":"Contraseñas repetidas",
        "users_subscriptions":"Usuarios/Suscripciones",
        "main_categories":"Categorías principales",
        "main_users":"Usuarios principales",
        "email":"Email",
        "permission":"Permiso",
        "users":"Usuarios",
        "new_user":"Nuevo usuario",
        "ex_permission":"Ej.: ADMINISTRADOR",
        "remove_users":"Eliminar usuarios",
        "remove_users_desc":"¿Realmente desea eliminar el usuario seleccionado?<label class=\"custom-control custom-checkbox\"><input id=\"checkbox\" onclick=\"transfer()\" type=\"checkbox\" class=\"custom-control-input\"><span id=\"checkboxlabel\" class=\"custom-control-label\">Transferir a:</span></label><div class=\"form-group\" style=\"margin-top: 20px;\"><select class=\"selectpicker\" id=\"usertransfer\" disabled=true placeholder=\"Ex.: USER\" style=\"color: #fff; background: #262628;\" required></select>",
        "edit_user":"Editar usuario",
        "share":"Compartir",
        "warning":"Advertencia",
        "remove":"Eliminar",
        "warning_no_permission":"No tienes permisos para administrar itens compartidos.",
        "security":"Seguridad"
    }
    var de = 
    {
        "isenhas_title":"iSenhas | Passwort-Manager | Empfohlen im App Store",
        "search_vaults": "Tresore durchsuchen",
        "personal": "Persönlich",
        "vault": "Tresor",
        "passkeys": "Passkeys",
        "docsmenu": "<i class=\"fa fa-id-card\" ></i>Dokumente",
        "isenhas": "iSenhas",
        "description_label": "Notiz (optional)",
        "description_title": "Notiz",
        "favorite_pix": "Bevorzugter Überweisungscode",
        "favorite_note": "Bevorzugte Notiz",
        "favorite_password": "Bevorzugtes Passwort",
        "favorite_document": "Bevorzugtes Dokument",
        "search_notes": "Notizen durchsuchen",
        "search_notes_error": "Fehler beim Durchsuchen der Notizen. Seite aktualisieren und erneut versuchen. Code",
        "search_statistics_error": "Fehler beim Abrufen der Statistiken. Seite aktualisieren und erneut versuchen. Code",
        "add_note": "Notiz erstellen",
        "add_note_error": "Fehler beim Erstellen der Notiz. Seite aktualisieren und erneut versuchen. Code",
        "add_user": "Benutzer erstellen",
        "add_user_error": "Fehler beim Erstellen des Benutzers. Seite aktualisieren und erneut versuchen. Code",
        "no_selection": "Keine Notiz ausgewählt.",
        "remove_note": "Notizen entfernen",
        "remove_note_error": "Fehler beim Entfernen der Notizen. Seite aktualisieren und erneut versuchen. Code",
        "remove_user": "Benutzer entfernen",
        "remove_user_error": "Fehler beim Entfernen des Benutzers. Seite aktualisieren und erneut versuchen. Code",
        "update_note": "Notiz aktualisieren",
        "update_note_error": "Fehler beim Aktualisieren der Notiz. Seite aktualisieren und erneut versuchen. Code",
        "update_user": "Benutzer aktualisieren",
        "update_user_error": "Fehler beim Aktualisieren des Benutzers. Seite aktualisieren und erneut versuchen. Code",
        "search_passwords": "Passwörter durchsuchen",
        "search_passwords_error": "Fehler beim Durchsuchen der Passwörter. Seite aktualisieren und erneut versuchen. Code",
        "search_users": "Benutzer durchsuchen",
        "search_users_error": "Fehler beim Durchsuchen der Benutzer. Seite aktualisieren und erneut versuchen. Code",
        "add_password": "Passwort erstellen",
        "add_password_error": "Fehler beim Erstellen des Passworts. Seite aktualisieren und erneut versuchen. Code",
        "no_password_selected": "Kein Passwort ausgewählt",
        "no_user_selected": "Kein Benutzer ausgewählt",
        "remove_password": "Passwörter entfernen",
        "remove_document": "Dokumente entfernen",
        "remove_password_error": "Fehler beim Entfernen der Passwörter. Seite aktualisieren und erneut versuchen. Code",
        "update_password": "Passwort aktualisieren",
        "update_document": "Dokument aktualisieren",
        "update_password_error": "Fehler beim Aktualisieren des Passworts. Seite aktualisieren und erneut versuchen. Code",
        "code_notfound": "Code nicht gefunden. Seite aktualisieren und erneut versuchen.",
        "login_error": "Fehler bei der Authentifizierung. Seite aktualisieren und erneut versuchen. Code",
        "weak": "Schwach",
        "very_weak": "Sehr schwach",
        "regular": "Angemessen",
        "strong": "Stark",
        "very_strong": "Sehr stark",
        "home": "START",
        "repeated": "Wiederholt",
        "about": "ÜBER UNS",
        "gallery": "GALERIE",
        "team": "TEAM",
        "download": "DOWNLOAD",
        "price": "PLÄNE",
        "contact": "KONTAKT",
        "my_passwords": "LOGIN",
        "title_start": "Passwörter intelligent und sicher verwalten.",
        "title_sub1": "Greifen Sie von überall aus per App, Website oder Browser-Erweiterung darauf zu.",
        "title_sub2": "Nutzen Sie den intelligenten Ordneralgorithmus und die automatische Ikon-Erkennung zur Organisation.",
        "title_sub3": "Erstellen Sie starke und zufällige Passwörter in einer sicheren, AES-256-verschlüsselten Umgebung.",
        "how_works": "Wie funktioniert es?",
        "how_works_sub": "Schnelle und einfache Einrichtung, um mit <br>biometrischem Sensor oder Ihrem Einzigartigen Passwort von jedem Gerät aus zuzugreifen.",
        "how_works_import": "Importieren",
        "how_works_import_sub": "Importieren Sie Ihre Passwörter aus Google, LastPass, Dashlane, Bitwarden, SafeInCloud oder benutzerdefinierten Dateien.",
        "how_works_generate": "Generieren",
        "how_works_generate_sub": "Erzeugen Sie starke Passwörter mit bis zu 30 Zeichen, einschließlich Sonderzeichen, Großbuchstaben und Zahlen.",
        "how_works_autofill": "Automatisches Ausfüllen",
        "how_works_autofill_sub": "Füllen Sie Login-Felder auf jedem Gerät schnell aus.",
        "how_works_scan": "Scannen",
        "how_works_scan_sub": "Überprüfen Sie die Sicherheit Ihrer Passwörter in der Warnliste und ergreifen Sie Maßnahmen zur Verbesserung.",
        "prepare_sub1": "iSenhas hat noch nie eine Sicherheitsverletzung erlitten. Sollte dennoch eine auftreten, ist Ihr vertraulicher Tresorinhalt nicht gefährdet.",
        "prepare_sub2": "Jedes Element wird vor der Speicherung im iSenhas-Cloud-Backup mit AES-256 verschlüsselt.",
        "prepare_sub4": "Für die Offline-Speicherung auf dem Gerät selbst verwendet iSenhas eine PBKDF2-Ableitung des Access-Passworts zur Verschlüsselung der Elemente und gewährleistet so maximalen Schutz auch ohne Internetverbindung.",
        "prepare_sub8":"iSenhas legt auch Wert auf Transparenz. Ein Teil des Quellcodes ist öffentlich und kann über GitHub abgerufen werden, sodass die Community die Entwicklung der Projektsicherheit analysieren, prüfen und überwachen kann.",
        "prepare_desc": "Erweiterte Sicherheit.",
        "prepare_title": "Ist iSenhas sicher?",
        "get_app": "APP HERUNTERLADEN",
        "explore_title": "Die Lösung entdecken",
        "explore_sub": "Sehen Sie sich die Details an, die wir auf jeder Seite vorbereitet haben,<br>um Ihre Passwort-Erfahrung zu verbessern.",
        "us_title": "Lernen Sie den Gründer kennen",
        "us_sub": "Der Kopf hinter iSenhas und die Idee unkomplizierter Sicherheit.",
        "davi_title": "Gründer",
        "davi_sub": "Davi ist der Ingenieur und Schöpfer von iSenhas.<p>Mit über 10 Jahren Erfahrung arbeitete er für multinationale Unternehmen und gewann Innovationspreise.",
        "lisi_title": "Managerin und Buchhalterin",
        "lisi_sub": "Absolventin in Verwaltung und Buchhaltung, führt sie iSenhas auf dem Weg, ein einfaches und nützliches Tool zu bleiben. Erfahrener in der Branche, definiert sie die strategische Planung und das Marketing des Produkts.",
        "review1": "Tolles und unkompliziertes App. Funktioniert perfekt. Ich empfehle es. Glückwunsch an den Entwickler.",
        "review2": "Super funktionale und praktische Anwendung, um sie zu nutzen. Früher hatte ich alle Passwörter im Notizbuch, ohne viel Privatsphäre. Mit der App ist es viel sicherer.",
        "review3": "Sehr intuitive App, erfüllt, was sie verspricht. Ich kann all meine Passwörter sicher speichern.",
        "android_user": "Android-Nutzer",
        "ios_user": "iOS-Nutzer",
        "download_title": "Download",
        "download_sub": "Klicken Sie auf eine der Optionen, um zum Store der jeweiligen Plattform weitergeleitet zu werden.<br>iSenhas wird nicht außerhalb offizieller Stores angeboten.",
        "ios_title": "iOS/MacOS-App",
        "ios_sub": "Laden Sie die App herunter, die zu den Top 100 der meistgeladenen Apps im App Store Brasilien gehört.",
        "android_title": "Android-App",
        "android_sub": "Verwalten Sie Ihre Passwörter auf Android-Tablets und Smartphones.",
        "chrome_title": "Chrome-Erweiterung",
        "chrome_sub": "Erhöhen Sie Ihre Geschwindigkeit beim Zugriff auf Websites mit der Chrome-Erweiterung.",
        "brave_title": "Brave-Erweiterung",
        "brave_sub": "Steigern Sie Ihre Sicherheit beim Surfen im Brave-Browser.",
        "edge_title": "Edge-Erweiterung",
        "edge_sub": "Erhöhen Sie Ihre Produktivität im offiziellen Microsoft-Browser.",
        "firefox_title": "Firefox-Erweiterung",
        "firefox_sub": "Passwörter im Firefox-Browser verwalten und ausfüllen.",
        "safari_title": "Safari-Erweiterung",
        "safari_sub": "Nutzen Sie iSenhas im offiziellen Apple-Browser.",
        "questions_title": "Unsere Antworten auf die häufigsten Fragen",
        "questions1": "Hat jemand Zugriff auf meine Passwörter?",
        "questions1_answer": "Nein. Sie sind unser Kunde und nicht unser Produkt. Ihre Passwörter sind so geschützt, dass niemand außer Ihnen darauf zugreifen kann.",
        "questions2": "Hat jemand Zugriff auf meine Passwörter?",
        "questions2_answer": "Nein. Sie sind unser Kunde und nicht unser Produkt. Ihre Passwörter sind so geschützt, dass niemand außer Ihnen darauf zugreifen kann.",
        "questions3_answer": "Kompatibilität: Passwortmanager-Programme sind plattformübergreifend. Browser-Passwortmanager nicht: Sie sind auf diesen Browser beschränkt.<br>Passwortgenerator: Der größte Feind Ihrer Konten online ist Passwort-Wiederverwendung. Wird ein Passwort gehackt, sind alle anderen Konten gefährdet. Dadurch ist es für Angreifer einfach, sich Zugang zu verschaffen.",
        "questions3": "Warum iSenhas statt des Passwort-Managers im Browser verwenden?",
        "questions4_answer": "Ja. Sie können auch Notizen und Erinnerungen sicher speichern.",
        "questions4": "Kann ich außer Passwörtern noch etwas speichern?",
        "years_appstore": "Jahre im App Store",
        "happy_customers": "Zufriedene Kunden",
        "top_appstore": "Top App Store Brasilien",
        "cups_coffe": "Tassen Kaffee",
        "fast_support": "Schneller Support",
        "plans_title": "Pläne",
        "plans_sub": "Sehen Sie die verfügbaren Pläne im Google Play Store und im App Store.<br>Sie können sie direkt in den Apps erwerben.",
        "plans_free": "KOSTENLOS",
        "plans_price": "0,00 $",
        "plans_month": "Pro Monat",
        "plans_get": "APP HERUNTERLADEN",
        "plan1_arg1": "<b>Lokale</b> Speicherung von bis zu 5 Passwörtern.",
        "plan1_arg2": "Algorithmus für intelligente <b>Ordner</b>.",
        "plan1_arg3": "<b>Automatische</b> Ikon-Erkennung.",
        "plan1_arg4": "<b>Passwortgenerator</b>.",
        "plan1_arg5": "Liste mit Sicherheits-<b>Warnungen</b>.",
        "plan1_arg6": "<b>Automatisches</b> Ausfüllen von Logins.",
        "plan1_arg7": "3 Dark-Web-Scans auf <b>Datenlecks</b>.",
        "plan3_arg6": "24/7-Support.",
        "premium_price": "1,99 $",
        "plan2_arg1": "<b>Unbegrenzte Cloud</b>-Speicherung.",
        "plan2_arg2": "<b>Alle</b> Funktionen des kostenlosen Plans.",
        "plan2_arg3": "<b>Unbegrenzte</b> Dark-Web-Scans.",
        "plan2_arg4": "Passwortspeicherung <b>in der Cloud</b>.",
        "plan2_arg5": "Liste mit Sicherheitswarnungen.",
        "plan2_arg6": "Automatisches Ausfüllen von Logins.",
        "plan2_arg7": "<b>Sicheres</b> Teilen von Passwörtern.",
        "plan2_arg8": "Zugriff auf Ihre Passwörter auf <b>jedem Gerät</b>.",
        "plan2_arg9": "Passwort-<b>Wiederherstellung</b>.",
        "news_title": "Neuigkeiten",
        "news_sub": "Bleiben Sie über unsere Arbeit, neue Funktionen und Erfolge informiert.",
        "achievements": "Erfolge",
        "achievements_sub": "iSenhas wurde von Apple in der Liste „Beliebte Apps“ hervorgehoben.",
        "know_more": "MEHR ERFAHREN",
        "new2_title": "Wie verwendet man iSenhas am Computer?",
        "new2_sub1": "Videos",
        "new2_sub2": "Tutorial",
        "new2_desc": "Sehen Sie, wie einfach und sicher die Nutzung von iSenhas auf dem Computer ist.",
        "new3_title": "Wer macht iSenhas?",
        "new3_sub1": "Davi Orzechowski",
        "new3_sub2": "Gründer",
        "new3_desc": "Möchten Sie etwas über die Geschichte von iSenhas erfahren? Dieses Video zeigt den Anfang unserer Reise.",
        "contact_title": "Kontaktieren Sie uns",
        "contact_sub": "Fehlt etwas oder haben Sie ein Problem gefunden? Schreiben Sie uns.<br>Wir antworten so schnell wie möglich.",
        "contact_name": "Vollständiger Name*",
        "contact_email": "E-Mail*",
        "contact_text": "Schreiben Sie uns hier! Um den Service zu beschleunigen, geben Sie bitte Ihr Betriebssystem an (iOS oder Android).",
        "contact_send": "SENDEN",
        "contact_ok": "Vielen Dank für Ihre Nachricht. Wir melden uns so schnell wie möglich.",
        "img1": "/images/senha-en.webp",
        "img2": "/images/pastas-en.webp",
        "img3": "/images/alertas-en.webp",
        "img4": "/images/web-en.webp",
        "img5": "/images/chrome-en.webp",
        "img6": "/images/login-en.webp",
        "googlesafe": "/images/googlesafe-en.png",
        "popularapps": "/images/popularapps.png",
        "appswelove": "/images/appswelove.png",
        "apple_ecamp": "/images/apple_ecamp.png",
        "appswelove_link": "https://www.instagram.com/p/C-3u1XjJeON/",
        "popularapps_link": "https://www.instagram.com/p/C92SvgRO3Ku/",
        "social": "Finden Sie uns in sozialen Netzwerken:",
        "business_price": "1,10 $",
        "business_month": "pro Benutzer/Monat",
        "business_get": "APP HERUNTERLADEN",
        "business_download": "PDF HERUNTERLADEN",
        "plan3_arg1": "Premium-Funktionen für <b>alle Benutzer</b>.",
        "plan3_arg2": "Benutzerverwaltung mit <b>Profilen</b>.",
        "plan3_arg3": "Eigene Oberfläche zur Passwort-<b>Verwaltung</b>.",
        "plan3_arg4": "<b>Warnliste</b> für Sicherheit.",
        "users": "Benutzer",
        "add_user_limit": "Das Benutzerlimit wurde erreicht. Bitte kontaktieren Sie den iSenhas-Vertrieb, um Ihren Business-Plan zu erweitern.",
        "add_user_already_exists": "Dieser Benutzer existiert bereits. Fehler",
        "search_statistics": "Statistiken werden abgerufen. Dies kann etwas dauern",
        "bank": "Banken",
        "gov": "Behörden",
        "market": "Geschäfte",
        "travel": "Reisen",
        "document": "Dokumente",
        "internet": "Betreiber",
        "website": "Websites | Apps",
        "access": "Zugriff",
        "magazine": "Magazine",
        "other": "Andere",
        "notes": "Notizen",
        "strong_password": "Stark",
        "regular_password": "Normal",
        "weak_password": "Schwach",
        "shared_by": "Geteilt von",
        "share": "Teilen",
        "plan3_arg5": "<b>Teilen</b> von Passwörtern zwischen Benutzern.",
        "sending_notifications": "Benachrichtigungen werden gesendet",
        "passwords": "Passwörter",
        "login_title": "iSenhas WEB",
        "login_desc1": "1. Öffnen Sie die <b>iSenhas</b>-App, tippen Sie auf die<img style=\"height:30px;width: 30px;margin-left: 5px;margin-right: 5px;margin-bottom: 5px;\" alt=\"Qries\" src=\"/images/iconsmart/readbutton.png\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@fat\"/>Taste und authentifizieren Sie sich mit dem obigen <b>QR-Code</b> (für Premium-Benutzer).</h3>",
        "login_desc2": "2. Klicken Sie auf <b>ANMELDEN</b>, um iSenhas WEB zu öffnen.",
        "btn_login": "ANMELDEN",
        "login_loading": "Benutzer wird gesucht und sichere Umgebung vorbereitet...",
        "login_checkbox": "Angemeldet bleiben",
        "notas_loading": "Notizen werden gesucht...",
        "name": "Name",
        "password": "Passwort",
        "copy": "Kopieren",
        "note_search": "Notiz suchen...",
        "edit": "Bearbeiten",
        "passwordsmenu": "<i class=\"fas fa-key\" ></i>Passwörter",
        "notesmenu": "<i class=\"fas fa-sticky-note\" ></i>Notizen",
        "logoutmenu": "<i class=\"fas fa-sign-out-alt\" ></i>Abmelden",
        "notes": "Notizen",
        "buttonadd": "HINZUFÜGEN",
        "buttonremove": "ENTFERNEN",
        "new_note": "Neue Notiz",
        "note": "Notiz",
        "ex_note": "Bsp.: Meine Notiz",
        "ex_note_desc": "Bsp.: fea8hjaejJ(U",
        "cancelbutton": "ABBRECHEN",
        "remove_notes": "Notizen entfernen",
        "remove_notes_desc": "Möchten Sie die ausgewählten Notizen wirklich entfernen?",
        "edit_note": "Notiz bearbeiten",
        "savebutton": "SPEICHERN",
        "alertsmenu": "<i class=\"fas fa-exclamation-triangle\" ></i>Warnungen",
        "usersmenu2": "<i class=\"fas fa-users\" ></i>Benutzer",
        "estatisticasmenu2": "<i class=\"fas fa-chart-pie\"></i>Statistiken",
        "strength": "Stärke",
        "show": "Anzeigen",
        "search_password": "Passwort suchen...",
        "alerts": "Warnungen",
        "new_password": "Neues Passwort",
        "username": "Benutzername",
        "username_label": "Benutzername (optional)",
        "ex_password_name": "Bsp.: Mein Passwort",
        "ex_username": "Bsp.: username@email.com",
        "remove_passwords": "Passwörter entfernen",
        "remove_documents": "Dokumente entfernen",
        "remove_documents_desc": "Möchten Sie die ausgewählten Dokumente wirklich entfernen?",
        "remove_passwords_desc": "Möchten Sie die ausgewählten Passwörter wirklich entfernen?",
        "edit_password": "Passwort bearbeiten",
        "edit_document": "Dokument bearbeiten",
        "search_statistics": "Statistiken werden gesucht...",
        "search_user": "Benutzer suchen...",
        "general": "Allgemein",
        "statistics": "Statistiken",
        "health": "Sicherheit",
        "total_passwords": "Gesamt",
        "repeated_passwords": "Wiederholte Passwörter",
        "users_subscriptions": "Benutzer/Abonnements",
        "main_categories": "Hauptkategorien",
        "main_users": "Hauptbenutzer",
        "email": "E-Mail",
        "permission": "Berechtigung",
        "new_user": "Neuer Benutzer",
        "ex_permission": "Bsp.: ADMIN",
        "remove_users": "Benutzer entfernen",
        "remove_users_desc": "Möchten Sie den ausgewählten Benutzer wirklich entfernen?<label class=\"custom-control custom-checkbox\"><input id=\"checkbox\" onclick=\"transfer()\" type=\"checkbox\" class=\"custom-control-input\"><span id=\"checkboxlabel\" class=\"custom-control-label\">Übertragen an:</span></label><div class=\"form-group\" style=\"margin-top: 20px;\"><select class=\"selectpicker\" id=\"usertransfer\" disabled=true placeholder=\"Bsp.: USER\" style=\"color: #fff; background: #262628;\" required></select>",
        "edit_user": "Benutzer bearbeiten",
        "warning": "Warnung",
        "remove": "Entfernen",
        "warning_no_permission": "Sie haben keine Berechtigung, geteilte Elemente zu verwalten.",
        "pixmenu": "<iconify-icon icon=\"fa6-brands:pix\" style=\"padding-right:10px;\"> </iconify-icon>Sofortüberweisungscodes",
        "search_pix": "Sofortüberweisungscodes durchsuchen",
        "pixs": "Sofortüberweisungscodes",
        "pix": "Sofortüberweisungscode",
        "new_pix": "Sofortüberweisungscode hinzufügen",
        "description": "Beschreibung",
        "description_optional": "Beschreibung (optional)",
        "ex_pix_name": "Bsp.: John Mayer",
        "ex_pix_desc": "Bsp.: 548.964.147-23",
        "ex_description": "Bsp.: Kollege von der Arbeit",
        "remove_pix": "Sofortüberweisungscodes entfernen",
        "remove_pix_desc": "Möchten Sie die ausgewählten Codes wirklich entfernen?",
        "edit_pix": "Sofortüberweisungscode bearbeiten",
        "search_pix_s": "Sofortüberweisungscode suchen...",
        "search_pix_error": "Fehler beim Durchsuchen der Sofortüberweisungscodes. Seite aktualisieren und erneut versuchen. Code",
        "update_pix": "Sofortüberweisungscode aktualisieren",
        "update_pix_error": "Fehler beim Aktualisieren des Codes. Seite aktualisieren und erneut versuchen. Code",
        "add_pix": "Sofortüberweisungscode erstellen",
        "add_pix_error": "Fehler beim Erstellen des Codes. Seite aktualisieren und erneut versuchen. Code",
        "remove_pixs": "Sofortüberweisungscodes entfernen",
        "remove_pixs_error": "Fehler beim Entfernen der Sofortüberweisungscodes. Seite aktualisieren und erneut versuchen. Code",
        "capital_letters": "Großbuchstaben (A-Z)",
        "small_letters": "Kleinbuchstaben (a-z)",
        "numbers": "Zahlen (1-9)",
        "special_char": "Sonderzeichen",
        "length": "Länge",
        "documents": "Dokumente",
        "search_document": "Dokument suchen...",
        "expiration_date": "Ablaufdatum",
        "identification_code": "Identifikationscode",
        "new_document": "Neues Dokument",
        "expiration_label": "Ablaufdatum (optional)",
        "search_documents": "Dokumente durchsuchen",
        "ex_doc_name": "Bsp.: Reisepass",
        "ex_doc_desc": "Bsp.: 2841299245",
        "ex_doc_expiration": "Bsp.: 10/2025",
        "add_document": "Dokument erstellen",
        "privacy": "Datenschutzrichtlinie",
        "privacy-href": "https://isenhas.com.br/privacy-en.html",
        "update_shared_password": "Es ist nicht erlaubt, ein Element zu oder von einem geteilten Tresor zu übertragen.",
        "security": "Sicherheit",
        "new1_title": "Auf der  App Store Startseite hervorgehoben",
        "business_free": "TEAMS",
        "prepare_sub5": "Neben Sicherheit garantiert iSenhas auch Komfort. Wenn Sie den Zugang zu Ihrem Konto verlieren oder das Zugangspasswort vergessen, gibt es Wiederherstellungsmechanismen und technischen Support, um Ihnen zu helfen, ohne Risiko, Ihre Daten zu verlieren.",
        "prepare_sub6": "Die perfekte Balance zwischen fortschrittlichem Schutz und der Gewissheit, dass Ihre Passwörter immer verfügbar sein werden, wenn Sie sie brauchen.",
        "recovery_title": "Extreme Privatsphäre aktiviert",
        "recovery_key": "Wiederherstellungsschlüssel",
        "recovery_desc1": "1. Geben Sie den Wiederherstellungsschlüssel ein, um die Elemente zu entschlüsseln.",
        "recovery_nomeedit": "Bsp.: EWBW9D-APV01V-1LE2OF-COHNHR-0JMKSO-C7",
        "recovery_loadinglabel": "Wiederherstellungsschlüssel wird überprüft...",
        "recovery_login_error": "Falscher Wiederherstellungsschlüssel. Seite neu laden und erneut versuchen",
        "feature_not_available_extreme": "Diese Funktion wird noch für Benutzer mit aktivierter Extreme Privatsphäre entwickelt.",
        "wrong_recovery_key": "Falscher Wiederherstellungsschlüssel",
        "prepare_sub7": "Zusätzlich bietet iSenhas die Option Extreme Privatsphäre – eine Zero-Knowledge-Architektur. In diesem Modus werden Elemente mit AES-256-GCM mittels Wiederherstellungsschlüssel verschlüsselt, bevor sie im Cloud-Backup gespeichert werden. Nicht einmal das iSenhas-Team hat Zugriff auf die Inhalte."
    }

    var language =  navigator.language || navigator.userLanguage; 
    if(!language.includes("pt")){
        if(!language.includes("es")){
            if(!language.includes("de")){
                return en[id]
            } else {
                return de[id]
            }
        } else {
            return es[id]
        }
    } else {
        return pt[id]
    }
    //return de[id]
}